In [22]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import LabelEncoder

from sklearn.preprocessing import StandardScaler

In [26]:
df2 = pd.read_csv("insurance.csv")

In [28]:
df2.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [29]:
df2.shape

(1338, 7)

In [30]:
df2.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [31]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [35]:
# One-Hot Encoding işlemi
df2 = pd.get_dummies(df2, columns=['sex', 'smoker'], drop_first=True)

# Sonuçları kontrol edelim
df2.tail()

KeyError: "None of [Index(['sex', 'smoker'], dtype='object')] are in the [columns]"

In [34]:
# 'region' sütununu sayısal değerlere dönüştürme
label_encoder = LabelEncoder()
df2['region'] = label_encoder.fit_transform(df2['region'])

# Sonuçları kontrol edelim
df2.tail()

      age    bmi  children  region     charges  sex_male  smoker_yes
1333   50  30.97         3       1  10600.5483      True       False
1334   18  31.92         0       0   2205.9808     False       False
1335   18  36.85         0       2   1629.8335     False       False
1336   21  25.80         0       3   2007.9450     False       False
1337   61  29.07         0       1  29141.3603     False        True

In [ ]:
3 southwest
2 southeast
1 northwest
0 northeast

In [36]:
df2.to_csv("processed_data.csv", index=False)